### ISSUE TITLE
Editing .Less file using Visual Studio code often locks file

### ISSUE THREAD

**Issue by dodyg** [statiqdev/Statiq#108]
Editing .less file in Visual Studio often generates this error. This is similar to #92 .

```
Error while executing module ReadFiles: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'F:\Wyam\SilverKey\content\styles\site.less' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Wyam.Core.Modules.ReadFiles.<>c__DisplayClass11_2.<Execute>b__2(String file) in C:\Users\Dody\Documents\GitHub\Wyam\Wyam.Core\Modules\ReadFiles.cs:line 96
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c__DisplayClass0.<_cctor>b__1(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNext()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Wyam.Core.Pipelines.Pipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 documents) in C:\Users\Dody\Documents\GitHub\Wyam\Wyam.Core\Pipelines\Pipeline.cs:line 147
---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'F:\Wyam\SilverKey\content\styles\site.less' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Wyam.Core.Modules.ReadFiles.<>c__DisplayClass11_2.<Execute>b__2(String file) in C:\Users\Dody\Documents\GitHub\Wyam\Wyam.Core\Modules\ReadFiles.cs:line 96
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c__DisplayClass0.<_cctor>b__1(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

Command used

```
C:\Users\Dody\Documents\GitHub\Wyam\Wyam\bin\Debug\wyam.exe --input SilverKey --output c:\releases\SilverKey --noclean --watch --config SilverKey\config.wyam --preview
```

Pipeline

```
Pipelines.Add("Less",
  ReadFiles("site.less"),
  Less(),
  WriteFiles(".css")
);
```

**Comment by daveaglick** [comment]
I'm having a hard time replicating. First I tried a simple setup with the pipeline described here and couldn't get a lock up. Then I tried to replicate the folder structure exactly (based on the command line given) and ran the command in exactly the same way.

A couple questions:
- Does the Less file have any includes?
- In #92, the problem was partially triggered by using the outputs of one pipeline in a later pipeline - what does the entire config file look like?

**Comment by dodyg** [comment]
- No include
- Simple pipeline
- The problem shows up intermittent, however once it locks up, saving the file another time will tend to generate another error.

```
using System.IO;
using Wyam.Common;

---
Pipelines.Add("Less",
  ReadFiles("site.less"),
  Less(),
  WriteFiles(".css")
);

Pipelines.Add("Content",
    ReadFiles("*.md"),
    FrontMatter(Yaml()),
    Markdown(),
    Concat(
        ReadFiles("*.cshtml").Where(x => Path.GetFileName(x)[0] != '_'),
        FrontMatter(Yaml())     
    ),
    Razor(),
    WriteFiles(".html")
);

Pipelines.Add("Resources",
    CopyFiles("*").Where(x => Path.GetExtension(x) != ".cshtml" && !new[] { ".jpg", ".jpeg", ".gif", ".png", ".md"}.Contains(Path.GetExtension(x)))
);
```

Content of .less

```
@import url(https://fonts.googleapis.com/css?family=Roboto:400,100,700);
@import url(https://fonts.googleapis.com/css?family=Roboto+Slab:400,300,100,700);

@body-size: 20px;

@bottom-margin-between-text: @body-size + 2;
@body-color: #222;
@header-color: darkgrey;

@primary-color: #85A198;
@link-color: #2A5DB0;

@mobile: ~"only screen and (max-width: 529px)";

@orange:#F89D57;

body{
    font-family: 'Roboto', sans-serif;
    font-size: @body-size;
    line-height: 140%;
    color: @body-color;

    @media only screen and (max-width: 529px) {
        font-size: @body-size - 1;
    }
}

h1,h2,h3,h4,h5,h6{
    font-family: 'Roboto Slab', serif;
}

.home-jumbo {
    background: rgba(0,0,0,0.5); 
    border: 20px rgba(0,0,0,0.0) solid;
    border-radius: 20px;
    padding: 20px;
    p {
        margin-top:30px;
        color:white;
        font-size: 1.2rem;
    }
}

._2015, .expertise, .open-source, .topic-of-interests {
    h2{
        text-align: center;
        color: @orange;        
    }
}
```

**Comment by daveaglick** [comment]
Hopefully the PR resolves the issue. Just reopen if it looks like you still have problems.
