### ISSUE TITLE
Cannot generate examples site - RazorAndMarkdownBlog

### ISSUE THREAD

**Issue by ibebbs** [statiqdev/Statiq#112]
Hi,

I've downloaded (and unblocked) the latest Wyam.zip installation and cloned the Wyam repository, but when I try to generate the example RazorAndMarkdownBlog I get numerous errors.

I'm using the command (wyam is on the path):

`wyam .\Wyam\Examples\RazorAndMarkdownBlog`

And get the following output:

```
Wyam version 0.10.0-beta

   ,@@@@@       /@\        @@@@@       |                                        
   @@@@@@      @@@@@|     $@@@@@h      |                                        
  $@@@@@     ,@@@@@@@    g@@@@@P       |                                        
 ]@@@@@M    g@@@@@@@    g@@@@@P        |     @@P  @@@ ,@@%@  g$r,g@p   ,@@   ,@g
 $@@@@@    @@@@@@@@@   g@@@@@P         |    ]@@ ,@@@ ,$@` $@@@ g@P$@  ,@@@gg@@@@
j@@@@@   g@@@@@@@@@p ,@@@@@@@          |    $@g@@@9@@@@`  g@P g@$@$@@,@@ *P^`]@h
$@@@@@g@@@@@@@@B@@@@@@@@@@@P           |     *R^`  `BP   ?@`  B`  ?0` 0      ?P 
`$@@@@@@@@@@@`  ]@@@@@@@@@`            |                                        
  $@@@@@@@P`     ?$@@@@@P              |                                        
    `^``           *P*`                |                                        
Loading configuration from C:\Source\Repositories\Wyam\Examples\RazorAndMarkdownBlog\config.wyam
Cleaning output directory C:\Source\Repositories\Wyam\Examples\RazorAndMarkdownBlog\Output
Cleaned output directory.
Executing 2 pipelines
    Executing pipeline "Posts" (1/2) with 8 child module(s)
            Error while executing module ReadFiles: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Document source must be unique within the pipeline.
   at Wyam.Core.Pipelines.Pipeline.AddDocumentSource(String source) in E:\Code\Wyam\Wyam.Core\Pipelines\Pipeline.cs:line 263
   at Wyam.Core.Documents.Document.Clone(String source, Stream stream, IEnumerable`1 metadata, Boolean disposeStream) in E:\Code\Wyam\Wyam.Core\Documents\Document.cs:line 211
   at Wyam.Core.Modules.ReadFiles.<>c__DisplayClass11_2.<Execute>b__2(String file) in E:\Code\Wyam\Wyam.Core\Modules\ReadFiles.cs:line 89
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c__DisplayClass0.<_cctor>b__1(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNext()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Wyam.Core.Pipelines.Pipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 documents) in E:\Code\Wyam\Wyam.Core\Pipelines\Pipeline.cs:line 143
---> (Inner Exception #0) System.ArgumentException: Document source must be unique within the pipeline.
   at Wyam.Core.Pipelines.Pipeline.AddDocumentSource(String source) in E:\Code\Wyam\Wyam.Core\Pipelines\Pipeline.cs:line 263
   at Wyam.Core.Documents.Document.Clone(String source, Stream stream, IEnumerable`1 metadata, Boolean disposeStream) in E:\Code\Wyam\Wyam.Core\Documents\Document.cs:line 211
   at Wyam.Core.Modules.ReadFiles.<>c__DisplayClass11_2.<Execute>b__2(String file) in E:\Code\Wyam\Wyam.Core\Modules\ReadFiles.cs:line 89
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c__DisplayClass0.<_cctor>b__1(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

        Executed pipeline "Posts" (1/2) in 114 ms resulting in 0 output document(s)
    Executing pipeline "Home" (2/2) with 3 child module(s)
            1 errors compiling /home.cshtml:
/home.cshtml(5,21): error CS0021: Cannot apply indexing with [] to an expression of type 'IDocumentCollection'
            Error while executing module Razor: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Exception: /home.cshtml(5,21): error CS0021: Cannot apply indexing with [] to an expression of type 'IDocumentCollection'
   --- End of inner exception stack trace ---
   at Wyam.Modules.Razor.Microsoft.AspNet.Mvc.Razor.Compilation.RazorCompilationService.Compile(RelativeFileInfo file, String compilationContent) in E:\Code\Wyam\Wyam.Modules.Razor\Mvc\Microsoft.AspNet.Mvc.Razor\Compilation\RazorCompilationService.cs:line 125
   at Wyam.Modules.Razor.Microsoft.AspNet.Mvc.Razor.Compilation.RazorCompilationService.Compile(RelativeFileInfo file) in E:\Code\Wyam\Wyam.Modules.Razor\Mvc\Microsoft.AspNet.Mvc.Razor\Compilation\RazorCompilationService.cs:line 53
   at Wyam.Modules.Razor.Microsoft.AspNet.Mvc.Razor.VirtualPathRazorPageFactory.CreateInstance(String relativePath, Stream stream) in E:\Code\Wyam\Wyam.Modules.Razor\Mvc\Microsoft.AspNet.Mvc.Razor\VirtualPathRazorPageFactory.cs:line 75
   at Wyam.Modules.Razor.Microsoft.AspNet.Mvc.Razor.RazorViewEngine.GetRazorPageResult(ViewContext context, String pageName, Boolean isPartial, Stream stream) in E:\Code\Wyam\Wyam.Modules.Razor\Mvc\Microsoft.AspNet.Mvc.Razor\RazorViewEngine.cs:line 130
   at Wyam.Modules.Razor.Microsoft.AspNet.Mvc.Razor.RazorViewEngine.GetView(ViewContext context, String viewName, Stream stream) in E:\Code\Wyam\Wyam.Modules.Razor\Mvc\Microsoft.AspNet.Mvc.Razor\RazorViewEngine.cs:line 71
   at Wyam.Modules.Razor.Razor.<>c__DisplayClass7_0.<Execute>b__1(IDocument x) in E:\Code\Wyam\Wyam.Modules.Razor\Razor.cs:line 67
   at System.Threading.Tasks.Parallel.<>c__DisplayClass21`2.<ForEachWorker>b__22(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__11()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass0.<ExecuteSelfReplicating>b__1(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wyam.Modules.Razor.Razor.Execute(IReadOnlyList`1 inputs, IExecutionContext context) in E:\Code\Wyam\Wyam.Modules.Razor\Razor.cs:line 59
   at Wyam.Core.Pipelines.Pipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 documents) in E:\Code\Wyam\Wyam.Core\Pipelines\Pipeline.cs:line 142
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Exception: /home.cshtml(5,21): error CS0021: Cannot apply indexing with [] to an expression of type 'IDocumentCollection'
   --- End of inner exception stack trace ---
   at Wyam.Modules.Razor.Microsoft.AspNet.Mvc.Razor.Compilation.RazorCompilationService.Compile(RelativeFileInfo file, String compilationContent) in E:\Code\Wyam\Wyam.Modules.Razor\Mvc\Microsoft.AspNet.Mvc.Razor\Compilation\RazorCompilationService.cs:line 125
   at Wyam.Modules.Razor.Microsoft.AspNet.Mvc.Razor.Compilation.RazorCompilationService.Compile(RelativeFileInfo file) in E:\Code\Wyam\Wyam.Modules.Razor\Mvc\Microsoft.AspNet.Mvc.Razor\Compilation\RazorCompilationService.cs:line 53
   at Wyam.Modules.Razor.Microsoft.AspNet.Mvc.Razor.VirtualPathRazorPageFactory.CreateInstance(String relativePath, Stream stream) in E:\Code\Wyam\Wyam.Modules.Razor\Mvc\Microsoft.AspNet.Mvc.Razor\VirtualPathRazorPageFactory.cs:line 75
   at Wyam.Modules.Razor.Microsoft.AspNet.Mvc.Razor.RazorViewEngine.GetRazorPageResult(ViewContext context, String pageName, Boolean isPartial, Stream stream) in E:\Code\Wyam\Wyam.Modules.Razor\Mvc\Microsoft.AspNet.Mvc.Razor\RazorViewEngine.cs:line 130
   at Wyam.Modules.Razor.Microsoft.AspNet.Mvc.Razor.RazorViewEngine.GetView(ViewContext context, String viewName, Stream stream) in E:\Code\Wyam\Wyam.Modules.Razor\Mvc\Microsoft.AspNet.Mvc.Razor\RazorViewEngine.cs:line 71
   at Wyam.Modules.Razor.Razor.<>c__DisplayClass7_0.<Execute>b__1(IDocument x) in E:\Code\Wyam\Wyam.Modules.Razor\Razor.cs:line 67
   at System.Threading.Tasks.Parallel.<>c__DisplayClass21`2.<ForEachWorker>b__22(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__11()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass0.<ExecuteSelfReplicating>b__1(Object )
---> (Inner Exception #0) System.Exception: /home.cshtml(5,21): error CS0021: Cannot apply indexing with [] to an expression of type 'IDocumentCollection'<---
<---

        Executed pipeline "Home" (2/2) in 472 ms resulting in 0 output document(s)
    Executed 2 pipelines in 592 ms
```

I really like the philosophy behind wyam and would very much like to use it but I'm failing at the first hurdle here. Any ideas?

Thanks,
  Ian

**Comment by daveaglick** [comment]
Thanks for taking a look at the project! It turns out that there's a known bug for this example that's been fixed in the develop branch (see #78 and #102). You can either build from source or I can send you a new .zip of the most recent develop build. I'm hoping to get a new official release out next week with the fix.

**Comment by ibebbs** [comment]
Hey,

Thanks for the (amazingly quick) reply. I'll try building from the development branch and let you know how I get on.

Cheers,
  Ian

**Comment by ibebbs** [comment]
Hi,

Compiled wyam from source and the example sites generate fine.

Now to see if I can polish of my extremely rusty HTML skills and craft a halfway decent layout!

Thanks,
  Ian

**Comment by daveaglick** [comment]
:thumbsup: Just drop me a line here or on Gitter if you have any other questions.

**Comment by ibebbs** [comment]
One question, I notice your blog is CC licensed, mind if I use it as a basis for my own? My HTML skills are not what they once were (in fact, they're exactly what they once were but the world of HTML has moved on without me) and I'd like to get something online pretty quick.

I'll obviously link to Wyam. Would you like further attribution for the blog layout? More than happy, just let me know.

Cheers,
  Ian

**Comment by daveaglick** [comment]
Not at all! No attribution needed. In fact, the layout is just a customized version of the one here: http://startbootstrap.com/template-overviews/clean-blog/

**Comment by ibebbs** [comment]
Hi Dave,

Not sure if I broke something or there has been a breaking change in the development branch of Wyam but to get your blog to generate successfully I had to changed the "PostFile" metadata reference in 'home.cshtml' to "DestinationFilePath" (was previously getting a 'KeyNotFoundException' for the 'PostFile') value.

Does this sound right to you or have I missed something?

Cheers,
  Ian

**Comment by daveaglick** [comment]
I'm not surprised there may have been breaking changes - we're currently in "move fast and break things" mode. I haven't had a chance to check my blog for breaking changes yet, so you may have saved me some time :). Hopefully things will settle this week as we get close to the next release, which I'm targeting by the end of the week or early next week.

**Comment by ibebbs** [comment]
Gotcha. Well, you're not breaking too much it seems. Apart from this, I managed to regenerate your blog perfectly.

Now, let the blatant plagiarism commence ;0P
