### ISSUE TITLE
Error building Wyam blog - The partial view '_PostHeader' was not found.

### ISSUE THREAD

**Issue by gilessmith** [statiqdev/Statiq#339]
I am trying to generate a static blog using Wyam. I had this set up in the past and was working fine, but I am currently getting the following exception (full stack trace below).

_Exception during execution: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The partial view '_PostHeader' was not found. The following locations were searched:
/_PostHeader
/Shared/_PostHeader
/Views/_PostHeader
/Views/Shared/_PostHeader
/_PostHeader.cshtml
/Shared/_PostHeader.cshtml
/Views/_PostHeader.cshtml
/Views/Shared/_PostHeader.cshtml_

I have uninstalled Wyam and reinstalled. Then in a clean directory I have started a clean directory I have run the 2 commands from the tutorial: 

```
wyam.exe new --recipe Blog
wyam.exe --recipe Blog --theme CleanBlog
```

I notice that a recent [changeset](https://github.com/Wyamio/Wyam/commit/983814d230e516b4abc4ea56ee54a0dbb3895e0b) has changed the ViewLocationExpander and also altered the path for the _PostHeader template, and thought this issue may be related. 

Any ideas? 

Exception during execution: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The partial view '_PostHeader' was not found. The following locations were searched:
/_PostHeader
/Shared/_PostHeader
/Views/_PostHeader
/Views/Shared/_PostHeader
/_PostHeader.cshtml
/Shared/_PostHeader.cshtml
/Views/_PostHeader.cshtml
/Views/Shared/_PostHeader.cshtml
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.<RenderPartialCoreAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.<PartialAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperPartialExtensions.Partial(IHtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperPartialExtensions.Partial(IHtmlHelper htmlHelper, String partialViewName)
   at AspNetCore._posts__Layout_cshtml.<<ExecuteAsync>b__21_0>d.MoveNext() in /posts/_Layout.cshtml:line 6
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.<RenderSectionAsyncCore>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.RenderSection(String name, Boolean required)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.RenderSection(String name)
   at AspNetCore._posts_____Layout_cshtml.<ExecuteAsync>d__21.MoveNext() in /posts/../_Layout.cshtml:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderLayoutAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wyam.Razor.Razor.<>c__DisplayClass10_0.<Execute>b__2(IDocument input)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNext()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Wyam.Core.Execution.Pipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 documents) in E:\Code\Wyam\src\Wyam.Core\Execution\Pipeline.cs:line 189
   at Wyam.Core.Execution.Pipeline.Execute(Engine engine) in E:\Code\Wyam\src\Wyam.Core\Execution\Pipeline.cs:line 213
   at Wyam.Core.Execution.Engine.Execute() in E:\Code\Wyam\src\Wyam.Core\Execution\Engine.cs:line 162
---> (Inner Exception #0) System.InvalidOperationException: The partial view '_PostHeader' was not found. The following locations were searched:
/_PostHeader
/Shared/_PostHeader
/Views/_PostHeader
/Views/Shared/_PostHeader
/_PostHeader.cshtml
/Shared/_PostHeader.cshtml
/Views/_PostHeader.cshtml
/Views/Shared/_PostHeader.cshtml
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.<RenderPartialCoreAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.<PartialAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperPartialExtensions.Partial(IHtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperPartialExtensions.Partial(IHtmlHelper htmlHelper, String partialViewName)
   at AspNetCore._posts__Layout_cshtml.<<ExecuteAsync>b__21_0>d.MoveNext() in /posts/_Layout.cshtml:line 6
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.<RenderSectionAsyncCore>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.RenderSection(String name, Boolean required)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.RenderSection(String name)
   at AspNetCore._posts_____Layout_cshtml.<ExecuteAsync>d__21.MoveNext() in /posts/../_Layout.cshtml:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderLayoutAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wyam.Razor.Razor.<>c__DisplayClass10_0.<Execute>b__2(IDocument input)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by daveaglick** [comment]
I think this might be due to a bug I found shortly after publishing that's been fixed for the next release. Wyam is supposed to match package versions with the currently running version from now on, but themes weren't getting accounted for. The bug affects folks in your situation who've used a previous version and therefore have an old theme package lying around.

Can you try running it one more time with the `-u` flag and let me know if that resolves the problem? If so, you'll only have to add the flag once - once the newer version is downloaded you should be good to go from then on.

**Comment by gilessmith** [comment]
Hi Dave, 

Thank you for the incredibly quick feedback. 

Running with the -u flag fixed the issue. 

Thank you!

**Comment by daveaglick** [comment]
Great! That confirms this is (probably) an issue that's already been resolved (the best kind!). You shouldn't need to do anything else now that you've got the updated package. And the next version will update it automatically for you.
