### ISSUE TITLE
Uncaught exception when using unsupported tags format

### ISSUE THREAD

**Issue by snielsson** [statiqdev/Statiq#589]
If you try to use a tag with spaces/quotes like this in config.wyam:

Tags: "tag with space"

You get a nasty error. Could be handled more gracefully with an easier to understand error message if tags with spaces/quotes are not supported. 

    Executing pipeline "BlogPosts" (2/14) with 6 child module(s)
                    Exception while processing document file:///C:/projects/blogs/codingBlog/input/posts/index.md in module Yaml: (Line: 3, Col: 23, Idx: 98) - (Line: 3, Col: 35, Idx: 110): While parsing a block mapping, did not find expected key.
                    Error while executing module Yaml
                Exception while processing document file:///C:/projects/blogs/codingBlog/input/posts/index.md in module FrontMatter: One or more errors occurred.
                Error while executing module FrontMatter
            Error while executing module ModuleCollection
        Error while executing pipeline BlogPosts
Exception during execution: System.AggregateException: One or more errors occurred. ---> YamlDotNet.Core.SemanticErrorException: (Line: 3, Col: 23, Idx: 98) - (Line: 3, Col: 35, Idx: 110): While parsing a block mapping, did not find expected key.
   at YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst) in C:\projects\yamldotnet\YamlDotNet\Core\Parser.cs:line 709
   at YamlDotNet.Core.Parser.StateMachine() in C:\projects\yamldotnet\YamlDotNet\Core\Parser.cs:line 162
   at YamlDotNet.Core.Parser.MoveNext() in C:\projects\yamldotnet\YamlDotNet\Core\Parser.cs:line 111
   at YamlDotNet.Core.EventReader.Allow[T]() in C:\projects\yamldotnet\YamlDotNet\Core\EventReader.cs:line 109
   at YamlDotNet.Core.EventReader.Expect[T]() in C:\projects\yamldotnet\YamlDotNet\Core\EventReader.cs:line 66
   at YamlDotNet.RepresentationModel.YamlScalarNode..ctor(EventReader events, DocumentLoadingState state) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlScalarNode.cs:line 57
   at YamlDotNet.RepresentationModel.YamlNode.ParseNode(EventReader events, DocumentLoadingState state) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlNode.cs:line 84
   at YamlDotNet.RepresentationModel.YamlMappingNode..ctor(EventReader events, DocumentLoadingState state) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlMappingNode.cs:line 71
   at YamlDotNet.RepresentationModel.YamlNode.ParseNode(EventReader events, DocumentLoadingState state) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlNode.cs:line 94
   at YamlDotNet.RepresentationModel.YamlDocument..ctor(EventReader events) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlDocument.cs:line 72
   at YamlDotNet.RepresentationModel.YamlStream.Load(EventReader reader) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlStream.cs:line 103
   at YamlDotNet.RepresentationModel.YamlStream.Load(TextReader input) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlStream.cs:line 91
   at Wyam.Yaml.Yaml.<>c__DisplayClass4_0.<Execute>b__0(IDocument input)
   at Wyam.Common.Execution.TraceExceptionsExtensions.TraceExceptions[TResult](IExecutionContext context, IDocument document, Func`2 func)
   at Wyam.Common.Execution.TraceExceptionsExtensions.<>c__DisplayClass10_0.<SelectMany>b__0(IDocument x)
   at System.Linq.Parallel.SelectManyQueryOperator`3.SelectManyQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, Pair`2& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNext()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments)
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs, IEnumerable`1 items)
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs)
   at Wyam.Core.Modules.Control.FrontMatter.<>c__DisplayClass10_0.<Execute>b__0(IDocument input)
   at Wyam.Common.Execution.TraceExceptionsExtensions.TraceExceptions(IExecutionContext context, IDocument document, Action`1 action)
   at Wyam.Common.Execution.TraceExceptionsExtensions.ForEach(IExecutionContext context, IEnumerable`1 documents, Action`1 action)
   at Wyam.Core.Modules.Control.FrontMatter.Execute(IReadOnlyList`1 inputs, IExecutionContext context)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments)
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs, IEnumerable`1 items)
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs)
   at Wyam.Core.Modules.Extensibility.ModuleCollection.Execute(IReadOnlyList`1 inputs, IExecutionContext context)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(Engine engine, Guid executionId)
   at Wyam.Core.Execution.Engine.Execute()
---> (Inner Exception #0) YamlDotNet.Core.SemanticErrorException: (Line: 3, Col: 23, Idx: 98) - (Line: 3, Col: 35, Idx: 110): While parsing a block mapping, did not find expected key.
   at YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst) in C:\projects\yamldotnet\YamlDotNet\Core\Parser.cs:line 709
   at YamlDotNet.Core.Parser.StateMachine() in C:\projects\yamldotnet\YamlDotNet\Core\Parser.cs:line 162
   at YamlDotNet.Core.Parser.MoveNext() in C:\projects\yamldotnet\YamlDotNet\Core\Parser.cs:line 111
   at YamlDotNet.Core.EventReader.Allow[T]() in C:\projects\yamldotnet\YamlDotNet\Core\EventReader.cs:line 109
   at YamlDotNet.Core.EventReader.Expect[T]() in C:\projects\yamldotnet\YamlDotNet\Core\EventReader.cs:line 66
   at YamlDotNet.RepresentationModel.YamlScalarNode..ctor(EventReader events, DocumentLoadingState state) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlScalarNode.cs:line 57
   at YamlDotNet.RepresentationModel.YamlNode.ParseNode(EventReader events, DocumentLoadingState state) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlNode.cs:line 84
   at YamlDotNet.RepresentationModel.YamlMappingNode..ctor(EventReader events, DocumentLoadingState state) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlMappingNode.cs:line 71
   at YamlDotNet.RepresentationModel.YamlNode.ParseNode(EventReader events, DocumentLoadingState state) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlNode.cs:line 94
   at YamlDotNet.RepresentationModel.YamlDocument..ctor(EventReader events) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlDocument.cs:line 72
   at YamlDotNet.RepresentationModel.YamlStream.Load(EventReader reader) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlStream.cs:line 103
   at YamlDotNet.RepresentationModel.YamlStream.Load(TextReader input) in C:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlStream.cs:line 91
   at Wyam.Yaml.Yaml.<>c__DisplayClass4_0.<Execute>b__0(IDocument input)
   at Wyam.Common.Execution.TraceExceptionsExtensions.TraceExceptions[TResult](IExecutionContext context, IDocument document, Func`2 func)
   at Wyam.Common.Execution.TraceExceptionsExtensions.<>c__DisplayClass10_0.<SelectMany>b__0(IDocument x)
   at System.Linq.Parallel.SelectManyQueryOperator`3.SelectManyQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, Pair`2& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by snielsson** [comment]
and similar issue if you use a theme name that does not exist.

**Comment by daveaglick** [comment]
This appears to have been resolved somewhere along the way (probably with a YAML library update) and I can no longer replicate.
