### ISSUE TITLE
ValidateLinks in Docs recipe fails and always throws an error

### ISSUE THREAD

**Issue by tesar-tech** [statiqdev/Statiq#607]
Created new docs:
    `wyam new -r recipe`

Changed `config.wyam` to validate links:
```
Settings[DocsKeys.ValidateRelativeLinks] =true;
Settings[DocsKeys.ValidateAbsoluteLinks] =false;
Settings[DocsKeys.ValidateLinksAsError] =false; 
```
Run wyam with `watch` , `preview` and `verbose` 
`wyam -p -w -v `

And it throws some warnings in `ValidateLinks` pipeline:
 ``` powershell

 Validated relative link /assets/js/highlight.pack.js at assets/js/highlight.pack.js
                    Validation failure for relative link /assets/img/favicon.ico: could not find output file at any of 
assets/img/favicon.ico, assets/img/favicon.ico/index, assets/img/favicon.ico.htm, 
assets/img/favicon.ico/index.htm, assets/img/favicon.ico.html, assets/img/favicon.ico/index.html 
```

and also some errors:
```
  Validated relative link /docs at docs/index.html
                    Error while executing module ValidateLinks
                Error while executing module Execute
            Error while executing module If
        Error while executing pipeline ValidateLinks
Exception during execution: System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at Wyam.Html.ValidateLinks.AddOrUpdateFailure(ConcurrentBag`1 links, ConcurrentDictionary`2 failures)
   at Wyam.Html.ValidateLinks.<>c__DisplayClass6_0.<Execute>b__2(KeyValuePair`2 link)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wyam.Html.ValidateLinks.Execute(IReadOnlyList`1 inputs, IExecutionContext context)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionPipeline.cs:line 191
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs, IEnumerable`1 items) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionContext.cs:line 186
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionContext.cs:line 164
   at Wyam.Core.Modules.Extensibility.Execute.ExecuteModules(Object results, IExecutionContext context, IEnumerable`1 inputs) in E:\Code\Wyam\src\core\Wyam.Core\Modules\Extensibility\Execute.cs:line 152
   at Wyam.Core.Modules.Extensibility.Execute.Wyam.Common.Modules.IModule.Execute(IReadOnlyList`1 inputs, IExecutionContext context) in E:\Code\Wyam\src\core\Wyam.Core\Modules\Extensibility\Execute.cs:line 118
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionPipeline.cs:line 191
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs, IEnumerable`1 items) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionContext.cs:line 186
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionContext.cs:line 164
   at Wyam.Core.Modules.Control.If.Execute(IReadOnlyList`1 inputs, IExecutionContext context) in E:\Code\Wyam\src\core\Wyam.Core\Modules\Control\If.cs:line 141
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionPipeline.cs:line 191
   at Wyam.Core.Execution.ExecutionPipeline.Execute(Engine engine, Guid executionId) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionPipeline.cs:line 85
   at Wyam.Core.Execution.Engine.Execute() in E:\Code\Wyam\src\core\Wyam.Core\Execution\Engine.cs:line 260
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at Wyam.Html.ValidateLinks.AddOrUpdateFailure(ConcurrentBag`1 links, ConcurrentDictionary`2 failures)
   at Wyam.Html.ValidateLinks.<>c__DisplayClass6_0.<Execute>b__2(KeyValuePair`2 link)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

---> (Inner Exception #1) System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at Wyam.Html.ValidateLinks.AddOrUpdateFailure(ConcurrentBag`1 links, ConcurrentDictionary`2 failures)
   at Wyam.Html.ValidateLinks.<>c__DisplayClass6_0.<Execute>b__2(KeyValuePair`2 link)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
```

Reproducing this with `blog` recipe does not throw errors or warnings.

**Comment by daveaglick** [comment]
Sorry it took so long to address this bug - it'll be resolved in the next version.
