### ISSUE TITLE
Blog recipe - published date handling

### ISSUE THREAD

**Issue by dazinator** [statiqdev/Statiq#611]
As per: https://wyam.io/recipes/blog/overview

> Blog Post Published Dates
To find the published date for blog posts, the metadata will first be searched for a Published value. If one cannot be found (or it can't be converted to a DateTime) then the filename of the input file for the post will be checked for a date that appears in the beginning of the file name of the format YYYY-MM-DD-.

My post has the following front matter (originated from octopress)

```
published: true
```

It's filename starts with `2016-01-24-`

In this instance I would expect: 
> the filename of the input file for the post will be checked for a date that appears in the beginning of the file name of the format YYYY-MM-DD-.`

However what I encountered when doing ` wyam -r Blog -t CleanBlog -w -p` is the following:

```
 Executing pipeline "Feed" (7/14) with 3 child module(s)
            Exception while processing document file:///C:/Users/Darrell/Source/Repos/TestBlog/input/posts/2016-01-24-aurelia-and-asp-net-5-mvc-part2.md in module GenerateFeeds: Could not convert from type String to type Nullable`1 for file:///C:/Users/Darrell/Source/Repos/TestBlog/input/posts/2016-01-24-aurelia-and-asp-net-5-mvc-part2.md while reading published date for feed
            Error while executing module GenerateFeeds
        Error while executing pipeline Feed
Exception during execution: System.InvalidOperationException: Could not convert from type String to type Nullable`1 for file:///C:/Users/Darrell/Source/Repos/TestBlog/input/posts/2016-01-24-aurelia-and-asp-net-5-mvc-part2.md while reading published date for feed
   at Wyam.Common.Configuration.ConfigExtensions.Invoke[T](DocumentConfig config, IDocument document, IExecutionContext context, String errorDetails) in E:\Code\Wyam\src\core\Wyam.Common\Configuration\ConfigExtensions.cs:line 88
   at Wyam.Feeds.GenerateFeeds.<>c__DisplayClass53_0.<Execute>b__0(IDocument input)
   at Wyam.Common.Execution.TraceExceptionsExtensions.TraceExceptions(IExecutionContext context, IDocument document, Action`1 action) in E:\Code\Wyam\src\core\Wyam.Common\Execution\TraceExceptionsExtensions.cs:line 32
   at Wyam.Common.Execution.TraceExceptionsExtensions.ForEach(IExecutionContext context, IEnumerable`1 documents, Action`1 action) in E:\Code\Wyam\src\core\Wyam.Common\Execution\TraceExceptionsExtensions.cs:line 113
   at Wyam.Feeds.GenerateFeeds.Execute(IReadOnlyList`1 inputs, IExecutionContext context)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionPipeline.cs:line 191
   at Wyam.Core.Execution.ExecutionPipeline.Execute(Engine engine, Guid executionId) in E:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionPipeline.cs:line 85
   at Wyam.Core.Execution.Engine.Execute() in E:\Code\Wyam\src\core\Wyam.Core\Execution\Engine.cs:line 260

```

This is with wyam version 1.2.0 installed via chocolatey.

**Comment by daveaglick** [comment]
This does look like a bug - the file name should be used if `published` in front matter isn’t a date. What I can’t tell easily is if it’s failing when trying to convert the front matter value or the file name. Can you try removing all but a single post and deleting the `published` front matter from that post to see if that works?

**Comment by dazinator** [comment]
Sure, if i remove the published front matter completely, it works.

**Comment by daveaglick** [comment]
Thanks - definitely a bug in the try call then, it should be failing over to the filename. I’ll try to take a closer look in the next couple days.

**Comment by ReubenBond** [comment]
I hit this today. Removing the `Published:` frontmatter also worked for me.

**Comment by daveaglick** [comment]
> I’ll try to take a closer look in the next couple days.

Guess that never happened! :smile: :man_facepalming:

**Comment by daveaglick** [comment]
And I _finally_ got around to addressing this. The `Published` front matter will be checked first. If the `Published` front matter isn't a valid date according to the culture, it'll be ignored in favor of a date in the file name. If both are missing or invalid the post will get skipped and a warning will be output. The fix will go out with the next release.
