### ISSUE TITLE
Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

### ISSUE THREAD

**Issue by dazinator** [statiqdev/Statiq#667]
I just installed (updated) wyam 1.4.1 via chocolatey:
`choco update wyam`

And then ran the following in a clean working directory containing my blog posts and wyam config file only:

`wyam.exe --recipe Blog --theme CleanBlog`

It fails with:

> Executing pipeline "RenderBlogPosts" (8/14) with 5 child module(s)
            Exception while processing document file:///F:/Repos/TestBlog/input/posts/2016-01-24-aurelia-and-asp-net-5-mvc-part2.md in module Razor: Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
            Error while executing module Razor
        Error while executing pipeline RenderBlogPosts

Wyam does create the following files in my working directory when running this command:

![image](https://user-images.githubusercontent.com/3176632/40661385-85065784-634b-11e8-8b94-1aedf27a3c6b.png)

My `config.wyam` file looks like this:

```

#recipe Blog
#n Wyam.Html
// Customize your settings and add new ones here
Settings[Keys.Host] = "darrelltunnell.net";
Settings[BlogKeys.Title] = "My Blog";
Settings[BlogKeys.Description] = "Welcome!";
Settings[BlogKeys.PostsPath] = "posts";
Settings[BlogKeys.IndexPageSize] = 1;
Settings[BlogKeys.IndexFullPosts] = true;
Settings[BlogKeys.ArchivePageSize] = 10;
Settings[BlogKeys.ArchiveExcerpts] = true;
Settings[BlogKeys.IncludeDateInPostPath] = true;


// Add any pipeline customizations here
Console.WriteLine(String.Join(",", Pipelines.Keys.ToArray()));
Pipelines["BlogPosts"].Append(
  Meta(Keys.RelativeFilePath, (doc, ctx) =>
  {
    DateTime published = doc.Get<DateTime>(BlogKeys.Published);
    string fileName = doc.Bool("FrontMatterPublished")
      ? doc.FilePath(Keys.SourceFileName).ChangeExtension("html").FullPath
      : doc.FilePath(Keys.SourceFileName).ChangeExtension("html").FullPath.Substring(11);
    return $"{ctx.DirectoryPath(BlogKeys.PostsPath).FullPath}/{published:yyyy}/{published:MM}/{published:DD}/{fileName}";
    }));

```

<details>
  <summary>Here is the full build log:</summary>

>  **BUILD**
Loading configuration from file:///F:/Repos/TestBlog/config.wyam
Installing NuGet packages
    Installing packages to C:/Users/Administrator/.nuget/packages (using global packages folder)
    NuGet packages installed in 236 ms
Loading assemblies
    Assemblies loaded in 684 ms
Cataloging classes
    Classes cataloged in 422 ms
Evaluating configuration script
Pages,BlogPosts,Tags,TagIndex,BlogArchive,Index,Feed,RenderBlogPosts,RenderPages,Redirects,Less,Sass,Resources,ValidateLinks
    Evaluated configuration script in 3628 ms
Root path:
    file:///F:/Repos/TestBlog
Input path(s):
    file:///C:/Users/Administrator/.nuget/packages/Wyam.Razor.1.4.1/content
    file:///C:/Users/Administrator/.nuget/packages/Wyam.Blog.CleanBlog.1.4.1/content
    theme
    input
Output path:
    output
Temp path:
    temp
Using  as the JavaScript engine
Cleaning temp path: temp
Cleaned temp directory
Cleaning output path: output
Cleaned output directory
Executing 14 pipelines
    Executing pipeline "Pages" (1/14) with 4 child module(s)
        Executed pipeline "Pages" (1/14) in 588 ms resulting in 1 output document(s)
    Executing pipeline "BlogPosts" (2/14) with 7 child module(s)
        Executed pipeline "BlogPosts" (2/14) in 167 ms resulting in 17 output document(s)
    Executing pipeline "Tags" (3/14) with 4 child module(s)
        Executed pipeline "Tags" (3/14) in 4016 ms resulting in 17 output document(s)
    Executing pipeline "TagIndex" (4/14) with 1 child module(s)
        Executed pipeline "TagIndex" (4/14) in 79 ms resulting in 1 output document(s)
    Executing pipeline "BlogArchive" (5/14) with 1 child module(s)
        Executed pipeline "BlogArchive" (5/14) in 69 ms resulting in 2 output document(s)
    Executing pipeline "Index" (6/14) with 4 child module(s)
        Executed pipeline "Index" (6/14) in 136 ms resulting in 1 output document(s)
    Executing pipeline "Feed" (7/14) with 3 child module(s)
        Executed pipeline "Feed" (7/14) in 179 ms resulting in 2 output document(s)
    Executing pipeline "RenderBlogPosts" (8/14) with 5 child module(s)
            Exception while processing document file:///F:/Repos/TestBlog/input/posts/2016-01-24-aurelia-and-asp-net-5-mvc-part2.md in module Razor: Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
            Error while executing module Razor
        Error while executing pipeline RenderBlogPosts
Exception during execution: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at AspNetCore._posts_2016_01_DD_2016_01_24_aurelia_and_asp_net_5_mvc_part2_html.<ExecuteAsync>d__39.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at AspNetCore._posts_2016_01_DD_2016_01_24_aurelia_and_asp_net_5_mvc_part2_html.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wyam.Razor.RazorCompiler.RenderPage(RenderRequest request)
   at Wyam.Razor.RazorService.Render(RenderRequest request)
   at Wyam.Razor.Razor.<>c__DisplayClass16_0.<Execute>b__1(IDocument input)
   at Wyam.Common.Execution.TraceExceptionsExtensions.TraceExceptions[TResult](IExecutionContext context, IDocument document, Func`2 func)
   at Wyam.Common.Execution.TraceExceptionsExtensions.<>c__DisplayClass9_0.<Select>b__0(IDocument x)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNext()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(Engine engine, Guid executionId)
   at Wyam.Core.Execution.Engine.Execute()
---> (Inner Exception #0) System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Text.Encodings.Web, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at AspNetCore._posts_2016_01_DD_2016_01_24_aurelia_and_asp_net_5_mvc_part2_html.<ExecuteAsync>d__39.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at AspNetCore._posts_2016_01_DD_2016_01_24_aurelia_and_asp_net_5_mvc_part2_html.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wyam.Razor.RazorCompiler.RenderPage(RenderRequest request)
   at Wyam.Razor.RazorService.Render(RenderRequest request)
   at Wyam.Razor.Razor.<>c__DisplayClass16_0.<Execute>b__1(IDocument input)
   at Wyam.Common.Execution.TraceExceptionsExtensions.TraceExceptions[TResult](IExecutionContext context, IDocument document, Func`2 func)
   at Wyam.Common.Execution.TraceExceptionsExtensions.<>c__DisplayClass9_0.<Select>b__0(IDocument x)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

> WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
<---

</details>

**Comment by Roblinde** [comment]
I ran into the same thing today. Removing the `System.Text.Encoding.Web` assembly from my Wyam folder solved the problem for me for now.

**Comment by daveaglick** [comment]
I'm having a hard time reproducing this, but I know several folks have hit it. Can someone who's experiencing this problem (cc @elvogel) please see if adding the following to the `Wyam.exe.config` file resolves the issue (without removing the assembly):

```xml
<dependentAssembly>
  <assemblyIdentity name="System.Text.Encodings.Web" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-99.99.99.99" newVersion="4.0.1.1" />
</dependentAssembly>
```


If not, would you mind capturing a run using `--log --verbose` - that'll create a `wyam-[datetime].txt` file which you can cut and paste here or stick in a gist.

Thanks!

**Comment by dazinator** [comment]
@daveaglick @elvogel - sure, where is the wyam.exe.config file though? It doesn't appear to be along side the wyam.exe in the chocolatey directory? (C:\ProgramData\chocolatey\bin)

**Comment by dazinator** [comment]
nevermind, found it at: `C:\ProgramData\chocolatey\lib\wyam`

**Comment by dazinator** [comment]
@daveaglick @elvogel - I can confirm adding that assembly binding redirect above does prevent the error.

**Comment by daveaglick** [comment]
@dazinator Great, thanks a bunch for confirming that. I've added the binding redirect so it'll go out to everyone with the next release.

**Comment by elvogel** [comment]
Dave, just a quick update on this. 
I did an uninstall/reinstall of wyam using chocolatey. 

- Doing nothing, I get the assembly binding error. 
- When I add the config code, I still get the error. 
- When I delete the System.Text.Encodings.Web.dll from the wyam folder, it works
- When I go back and remove the assembly binding bits, it also works (dll is still deleted)

So the fix for me was making sure that DLL was never in that wyam folder to begin with.

**Comment by dazinator** [comment]
@elvogel I wonder why adding the binding redirect worked for me and not for you? Did you check the version of that assembly in the wyam folder to see if it macthed the redirect? I'll try your suggestion of removing it and deleting the assembly to see if that still works. If that way works for both of us then perhaps that is the better solution :-)
