### ISSUE TITLE
NuGetSources, #nuget-sources not working

### ISSUE THREAD

**Issue by lennoncork** [statiqdev/Statiq#673]
I have a Cake (0.26.1) build using Wyam (1.4.1) running on a TeamCity with no internet connectivity. I have a local drive providing NuGet packages, but I'm unable to get Wyam to honor the nuget-sources configuration. 

We have tried settings in wyam
```
    Wyam(new WyamSettings
    {
        Recipe = "Docs",
        Theme = "Samson",
        ...
        NuGetSources = new List<string> 
        {
            "<path-to-nuget-sources>",
        },
    });
```

We have also the following settings in config.wyam
#nuget-source "<path-to-nuget-sources>"

It looks like it ignores the additional nuget source, possibly because it's a network drive path not a NuGet server. The build server fails because it cannot access nuget.org. 

I am successfully able to configure Cake to use the external source. It would be good if Wyam could get it's nuget config from Cake, or even better a NuGet.config file.

**Comment by lennoncork** [comment]
I was able to get through some of the errors by manually copying packages to the build server's ".packages" directory. I still ended up with something looking to nuget.org. 

> [13:27:16][Step 1/2] Installing NuGet packages
[13:27:16][Step 1/2]     Installing packages to C:/Users/svc_cml_tc_agent/.nuget/packages (using global packages folder)
[13:27:16][Step 1/2]     Writing packages file to C:/TCBuildAgent-01/work/cc3ca3c32e61f346/....Docs/config.wyam.packages.xml
[13:27:16][Step 1/2]     Resolving package version for Wyam.Docs [1.4.1, 1.4.1] (with dependencies)
[13:27:16][Step 1/2]     Package Wyam.Docs [1.4.1, 1.4.1] is satisfied by version 1.4.1
[13:27:16][Step 1/2]     Resolving package version for Wyam.Docs.Samson [1.4.1, 1.4.1] (with dependencies)
[13:27:16][Step 1/2]     Package Wyam.Docs.Samson [1.4.1, 1.4.1] is satisfied by version 1.4.1
[13:27:16][Step 1/2]     Installing package Wyam.Docs 1.4.1
[13:27:17][Step 1/2]         
[13:27:17][Step 1/2] 
[13:27:17][Step 1/2]         Attempting to gather dependency information for package 'Wyam.Docs.1.4.1' with respect to project 'C:/Users/svc_cml_tc_agent/.nuget/packages', targeting 'Any,Version=v0.0'
[13:27:20][Step 1/2]     Exception while installing packages: Unable to load the service index for source https://api.nuget.org/v3/index.json.
[13:27:20][Step 1/2]     Error while installing packages, attempting without remote repositories
[13:27:20][Step 1/2]     Installing package Wyam.Docs 1.4.1
[13:27:20][Step 1/2]     Unexpected exception while installing packages: primarySources
[13:27:20][Step 1/2]     Error while installing packages, attempting to continue anyway
[13:27:20][Step 1/2]     NuGet packages installed in 3816 ms

The final resulting exception is
> [13:27:21][Step 1/2] Error while loading configuration: System.Exception: The recipe "Docs" could not be found
[13:27:21][Step 1/2]    at Wyam.Configuration.Configurator.ApplyRecipe() in E:\Code\Wyam\src\core\Wyam.Configuration\Configurator.cs:line 342
[13:27:21][Step 1/2]    at Wyam.Configuration.Configurator.Configure(String script, FilePath configFilePath) in E:\Code\Wyam\src\core\Wyam.Configuration\Configurator.cs:line 177
[13:27:21][Step 1/2]    at Wyam.Configuration.Configurator.Configure(IFile configFile) in E:\Code\Wyam\src\core\Wyam.Configuration\Configurator.cs:line 133
[13:27:21][Step 1/2]    at Wyam.Configuration.Configurator.Configure(FilePath configFilePath) in E:\Code\Wyam\src\core\Wyam.Configuration\Configurator.cs:line 116
[13:27:21][Step 1/2]    at Wyam.EngineManager.Configure() in E:\Code\Wyam\src\clients\Wyam\EngineManager.cs:line 122

**Comment by daveaglick** [comment]
Sorry it took so long to get back to you. I suspect NuGet is failing because "nuget.org" is configured as a default source in Wyam. NuGet gets funny when it can't access any of your sources, even if other ones are available and can service the request.

Unfortunately, this behavior is hard-coded right now so there's no way to turn off the "nuget.org" source. I'll add a `IgnoreDefaultPackageSources` that you can set to `true` to turn it off in the next version which should go out later this week or next week.

FWIW, Wyam is dropping all direct NuGet support in the forthcoming 2.x release (see #668). That's not to say NuGet packages won't still be involved, just that Wyam will no longer be responsible for handling their installation - MSBuild will do that going forward.

**Comment by daveaglick** [comment]
In the next version you'll be able to do the following, which will hopefully resolve your issues:

```c#
    Wyam(new WyamSettings
    {
        Recipe = "Docs",
        Theme = "Samson",
        ...
        NuGetSources = new List<string> 
        {
            "<path-to-nuget-sources>",
        },
        IgnoreDefaultSources = true
    });
```

If it doesn't please do circle back around and we'll reopen this issue.

**Comment by lennoncork** [comment]
@daveaglick thank you so much! Will keep you updated!

**Comment by lennoncork** [comment]
@daveaglick thoughts on a time frame for the next release?

**Comment by daveaglick** [comment]
@lennoncork Soonish - need to get Buildalyzer out the door first so the new version of Wyam can use it. That'll happen this week, so probably next week for a Wyam release (unless I find myself with tons of free time :rofl:)
