### ISSUE TITLE
Microsoft.Build.Exceptions.InvalidProjectFileException (Invalid static method invocation syntax) in Wyam 1.5.1

### ISSUE THREAD

**Issue by RichardJFoster** [statiqdev/Statiq#708]
Using Wyam 1.5.1, during the C# code analysis portion of a project that was analysed without errors using Wyam 1.4.1 the following exception is generated:

```
Exception during execution: Microsoft.Build.Exceptions.InvalidProjectFileException: Invalid static method invocation syntax: "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries($(TargetFrameworkIdentifier), $(TargetFrameworkVersion), $(TargetFrameworkProfile), $(PlatformTarget), $(TargetFrameworkRootPath), $(TargetFrameworkFallbackSearchPaths))". Method 'Microsoft.Build.Utilities.ToolLocationHelper.GetPathToStandardLibraries' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).   C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args) in /_/src/Shared/ProjectErrorUtilities.cs:line 412
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1) in /_/src/Shared/ProjectErrorUtilities.cs:line 98
   at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation) in /_/src/Build/Evaluation/Expander.cs:line 3281
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertyBody(String propertyBody, Object propertyValue, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties) in /_/src/Build/Evaluation/Expander.cs:line 1198
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties) in /_/src/Build/Evaluation/Expander.cs:line 1039
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties) in /_/src/Build/Evaluation/Expander.cs:line 896
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation) in /_/src/Build/Evaluation/Expander.cs:line 265
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyElement(ProjectPropertyElement propertyElement) in /_/src/Build/Evaluation/Evaluator.cs:line 1446
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyGroupElement(ProjectPropertyGroupElement propertyGroupElement) in /_/src/Build/Evaluation/Evaluator.cs:line 1087
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport) in /_/src/Build/Evaluation/Evaluator.cs:line 954
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement) in /_/src/Build/Evaluation/Evaluator.cs:line 1825
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport) in /_/src/Build/Evaluation/Evaluator.cs:line 997
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement) in /_/src/Build/Evaluation/Evaluator.cs:line 1825
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport) in /_/src/Build/Evaluation/Evaluator.cs:line 997
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement) in /_/src/Build/Evaluation/Evaluator.cs:line 1825
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport) in /_/src/Build/Evaluation/Evaluator.cs:line 997
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement) in /_/src/Build/Evaluation/Evaluator.cs:line 1825
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport) in /_/src/Build/Evaluation/Evaluator.cs:line 997
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext) in /_/src/Build/Evaluation/Evaluator.cs:line 726
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings) in /_/src/Build/Definition/Project.cs:line 2752
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings) in /_/src/Build/Definition/Project.cs:line 2719
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 2183
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) in /_/src/Build/Definition/Project.cs:line 2822
   at Buildalyzer.ProjectAnalyzer.Load(String targetFramework, BuildEnvironment buildEnvironment)
   at Buildalyzer.ProjectAnalyzer.BuildTargets(BuildEnvironment buildEnvironment, String targetFramework, String[] targetsToBuild)
   at Buildalyzer.ProjectAnalyzer.Build(String targetFramework, BuildEnvironment buildEnvironment)
   at Wyam.CodeAnalysis.ReadWorkspace.CompileProjectAndTrace(ProjectAnalyzer analyzer, StringWriter log)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Wyam.CodeAnalysis.AnalyzeCSharp.AddSolutionReferences(IExecutionContext context, List`1 symbols, Compilation compilation)
   at Wyam.CodeAnalysis.AnalyzeCSharp.Execute(IReadOnlyList`1 inputs, IExecutionContext context)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(Engine engine, Guid executionId)
   at Wyam.Core.Execution.Engine.Execute()
```
Wyam is being triggered from within Cake.

The only change between the functioning previous build was in the cake script. Specifically the referenced version for the Wyam tool and the Cake.Wyam add-in was changed in both cases from 1.4.1 to 1.5.1.

The version of Cake itself remained pinned at 0.28.1.

All suggestions for what might be causing this welcomed. :-)

**Comment by daveaglick** [comment]
Buildalyzer, which provides the project building support for Wyam, was rewritten extensively under the hood for the 1.5.1 release. It can build _a lot_ more projects than the old version, but the MSBuild APIs continue to provide headaches. It's a little bit like a game of whack-a-mole - you fix building for two types of projects but then cause a regression in a third.

Is the project being documented OSS or available somewhere? If not, are you at least able to share what the project file looks like?

**Comment by RichardJFoster** [comment]
Alas, the project being documented is closed source. I'm also not currently sure which of the 5 assemblies in the solution is the one this is getting triggered on. I'll poke around a bit and see what additional information I can dig out....

**Comment by RichardJFoster** [comment]
In case you haven't already spotted / heard this from other sources, based on our private conversation, whichever update it was to the build tools that triggered this issue also b0rks (at least) the 1.4.1 release. :-(

**Comment by RichardJFoster** [comment]
FWIW, I could have sworn that 1.4.1 was still working correctly when I first submitted this issue, but after a checkout to a "confirmed good" version and a `git clean -fdx` the problem was manifested.

**Comment by daveaglick** [comment]
Yeah, it's going to be retroactive since the problem is _probably_ due to incompatibilities between the current version of the MSBuild API used by Wyam/Buildalyzer and the latest SDK on the system. Update the installed SDK and it breaks all existing uses of the un-updated MSBuild APIs (and thus Buildalyzer and Wyam).

Actually working on this off and on today, hoping to at least get a little more info by the end of the day. Recently the approach that DoxFx takes of only building project files on Windows where VS is installed (I.e., using Roslyn's MsBuildWorkspace and related libraries) is sounding better and better. I'm getting awfully tired of spending so much time reverse-engineering generalized compatibility problems with MSBuild and the MSBuild APIs.

More to come...

**Comment by SilentSin** [comment]
I'm having this issue as well.

Removing the `<TargetFrameworkVersion>v3.5</TargetFrameworkVersion>` from the csproj lets it build the site but it fails to document the API at all.

**Comment by daveaglick** [comment]
@RichardJFoster based on your comments on Gitter, it sounds like this is no longer an issue for you with 1.6.0 - can you confirm? Given how Buildalyzer was re-architected, I would expect to see issues like this anymore.

@SilentSin can you confirm that you’re using Wyam 1.6.0 when you see this? And is the stack trace the same as described above or are you getting a slightly different error?

**Comment by RichardJFoster** [comment]
Oops... Yes, confirmed this is no longer an issue for me with Wyam 1.6.0.

**Comment by SilentSin** [comment]
From memory, the error I got was the same in 1.5.1 but I'm having a different issue with 1.6.0 so I'll post a separate issue for that.
