### ISSUE TITLE
ValidateAbsoluteLinks in the doc recipe causes a System.ObjectDisposedException

### ISSUE THREAD

**Issue by k94ll13nn3** [statiqdev/Statiq#759]
When using the docs recipe with Wyam version **2.1.0** with `DocsKeys.ValidateAbsoluteLinks` set to `true`, Wyam crashes with a `System.ObjectDisposedException`.

The bug can be reproduced by creating a new docs recipe and just changing the parameter.

I don't think that it is the same as #607 as I don't have any wanings during the validation.

I can reproduce also in 2.0.0 but it works in 1.7.4.

Stacktrace:
```
                    Error while executing module ValidateLinks
                Error while executing module Execute
            Error while executing module If
        Error while executing pipeline ValidateLinks
Exception during execution: System.AggregateException: One or more errors occurred. (Cannot access a disposed object.
Object name: 'System.Net.HttpWebResponse'.) (Cannot access a disposed object.
Object name: 'System.Net.HttpWebResponse'.) ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpWebResponse'.
   at System.Net.HttpWebResponse.CheckDisposed()
   at System.Net.HttpWebResponse.get_StatusCode()
   at Wyam.Html.ValidateLinks.ValidateAbsoluteLink(Uri uri, IExecutionContext context)
   at Wyam.Html.ValidateLinks.<>c__DisplayClass6_0.<Execute>b__2(KeyValuePair`2 link)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBef
oreCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBef
oreCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithSta
te, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithSta
te, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 body
WithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wyam.Html.ValidateLinks.Execute(IReadOnlyList`1 inputs, IExecutionContext context)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments) in C:\Code\Wyam\src\core\Wyam.Core\Execut
ion\ExecutionPipeline.cs:line 144
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs, IEnumerable`1 items) in C:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionCont
ext.cs:line 189
   at Wyam.Core.Modules.Extensibility.Execute.<>c__DisplayClass3_0.<.ctor>b__0(IReadOnlyList`1 inputs, IExecutionContext context) in C:\Code\Wyam\src\core\Wyam.Core\Modules\Ex
tensibility\Execute.cs:line 96
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments) in C:\Code\Wyam\src\core\Wyam.Core\Execut
ion\ExecutionPipeline.cs:line 144
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs, IEnumerable`1 items) in C:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionCont
ext.cs:line 189
   at Wyam.Core.Modules.Control.If.Execute(IReadOnlyList`1 inputs, IExecutionContext context) in C:\Code\Wyam\src\core\Wyam.Core\Modules\Control\If.cs:line 141
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments) in C:\Code\Wyam\src\core\Wyam.Core\Execut
ion\ExecutionPipeline.cs:line 144
   at Wyam.Core.Execution.ExecutionPipeline.Execute(Engine engine, Guid executionId) in C:\Code\Wyam\src\core\Wyam.Core\Execution\ExecutionPipeline.cs:line 85
   at Wyam.Core.Execution.Engine.Execute() in C:\Code\Wyam\src\core\Wyam.Core\Execution\Engine.cs:line 247
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpWebResponse'.
   at System.Net.HttpWebResponse.CheckDisposed()
   at System.Net.HttpWebResponse.get_StatusCode()
   at Wyam.Html.ValidateLinks.ValidateAbsoluteLink(Uri uri, IExecutionContext context)
   at Wyam.Html.ValidateLinks.<>c__DisplayClass6_0.<Execute>b__2(KeyValuePair`2 link)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBef
oreCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBef
oreCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

---> (Inner Exception #1) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpWebResponse'.
   at System.Net.HttpWebResponse.CheckDisposed()
   at System.Net.HttpWebResponse.get_StatusCode()
   at Wyam.Html.ValidateLinks.ValidateAbsoluteLink(Uri uri, IExecutionContext context)
   at Wyam.Html.ValidateLinks.<>c__DisplayClass6_0.<Execute>b__2(KeyValuePair`2 link)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBef
oreCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBef
oreCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
```

**Comment by daveaglick** [comment]
Yeah, this looks like a totally different issue than #607. If I recall, I had to port some of that code to other APIs for .NET Standard support. I suspect there’s a difference in expected object lifetime. Gut instinct is that this one won’t be too tough to track down.

**Comment by daveaglick** [comment]
I'm actually surprised this ever worked. I was calling `HttpWebResponse.Close()` before accessing the response object in certain control flows. Fixed now, will go out with next release early next week.
