### ISSUE TITLE
Non-Razor Page website asking for @page directive

### ISSUE THREAD

**Issue by elvogel** [statiqdev/Statiq#775]
I have a website built from scratch to support Wyam from before the 1.0 days; in fact, the last time I compiled it successfully was back in July 2018 (whatever version of Wyam that was - 1.4.1 I think). I just upgraded to the 2.1.2 version with .NET core and am in the process of making it compatible with ASP.NET Core. 

(To be clear - this site was never set up to use Razor Pages)

This website has several subfolders of information; one of them is a services/ folder containing the following:
- `_layout.cshtml`
- `_ViewStart.cshtml`
- `file1...file10.cshtml` Razor pages

My pipeline is configured as such:
```
#n Wyam.Markdown
#n Wyam.Razor
#n Wyam.Yaml
#n Wyam.Html 
#n Wyam.Feeds
#n Wyam.Minification
#n Wyam.SearchIndex

//cloud services directory
Pipelines.Add(
    "CloudServices",    
    ReadFiles("services/cloud/*.cshtml"),
    FrontMatter(Yaml()),
    Razor(),
    MinifyHtml().WithSettings(settings=> {
        settings.EmptyTagRenderMode = WebMarkupMin.Core.HtmlEmptyTagRenderMode.Slash;
        settings.RemoveTagsWithoutContent = false;
        settings.WhitespaceMinificationMode = WebMarkupMin.Core.WhitespaceMinificationMode.Safe;
        settings.RemoveOptionalEndTags = false;
        settings.AttributeQuotesRemovalMode = WebMarkupMin.Core.HtmlAttributeQuotesRemovalMode.KeepQuotes;
    }),
    WriteFiles(".html"),
    Meta("CloudServiceFile", string.Format(@"services/cloud/{0}", @doc.String("DestinationFileName"))),
    Meta("SitemapItem", ((string)@doc["CloudServiceFile"]).Replace(".html","").Replace("/index",""))
);
```
When this pipeline runs, I get the following output:
```
  Executing pipeline "CloudServices" (1/8) with 7 child module(s)
            Ignoring 2 inputs due to source file name prefix
            Exception while processing document file:///C:/Repos/websites/MywebsitE/wyam/input/services/cloud/file2.cshtml in module Razor: One or more compilation failures occurred:
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,55): Error RZ2005: The 'page` directive must appear at the start of the line.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,59): Error RZ1011: The 'page' directives value(s) must be separated by whitespace.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,54): Error RZ3906: The '@page' directive must precede all other elements defined in a Razor file.
            Exception while processing document file:///C:/Repos/websites/MywebsitE/wyam/input/services/cloud/page1.cshtml in module Razor: One or more compilation failures occurred:
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,55): Error RZ2005: The 'page` directive must appear at the start of the line.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,59): Error RZ1011: The 'page' directives value(s) must be separated by whitespace.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,54): Error RZ3906: The '@page' directive must precede all other elements defined in a Razor file.
            Exception while processing document file:///C:/Repos/websites/MywebsitE/wyam/input/services/cloud/index.cshtml in module Razor: One or more compilation failures occurred:
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,55): Error RZ2005: The 'page` directive must appear at the start of the line.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,59): Error RZ1011: The 'page' directives value(s) must be separated by whitespace.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,54): Error RZ3906: The '@page' directive must precede all other elements defined in a Razor file.
            Exception while processing document file:///C:/Repos/websites/MywebsitE/wyam/input/services/cloud/page2.cshtml in module Razor: One or more compilation failures occurred:
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,55): Error RZ2005: The 'page` directive must appear at the start of the line.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,59): Error RZ1011: The 'page' directives value(s) must be separated by whitespace.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,54): Error RZ3906: The '@page' directive must precede all other elements defined in a Razor file.
            Error while executing module Razor
        Error while executing pipeline CloudServices
Exception during execution: System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more compilation failures occurred:
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,55): Error RZ2005: The 'page` directive must appear at the start of the line.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,59): Error RZ1011: The 'page' directives value(s) must be separated by whitespace.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,54): Error RZ3906: The '@page' directive must precede all other elements defined in a Razor file.)) (One or more errors occurred. (One or more compilation failures occurred:
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,55): Error RZ2005: The 'page` directive must appear at the start of the line.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,59): Error RZ1011: The 'page' directives value(s) must be separated by whitespace.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,54): Error RZ3906: The '@page' directive must precede all other elements defined in a Razor file.)) (One or more errors occurred. (One or more compilation failures occurred:
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,55): Error RZ2005: The 'page` directive must appear at the start of the line.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,59): Error RZ1011: The 'page' directives value(s) must be separated by whitespace.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,54): Error RZ3906: The '@page' directive must precede all other elements defined in a Razor file.)) (One or more errors occurred. (One or more compilation failures occurred:
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,55): Error RZ2005: The 'page` directive must appear at the start of the line.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,59): Error RZ1011: The 'page' directives value(s) must be separated by whitespace.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,54): Error RZ3906: The '@page' directive must precede all other elements defined in a Razor file.)) (One or more compilation failures occurred:
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,55): Error RZ2005: The 'page` directive must appear at the start of the line.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,59): Error RZ1011: The 'page' directives value(s) must be separated by whitespace.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,54): Error RZ3906: The '@page' directive must precede all other elements defined in a Razor file.) (One or more compilation failures occurred:
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,55): Error RZ2005: The 'page` directive must appear at the start of the line.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,59): Error RZ1011: The 'page' directives value(s) must be separated by whitespace.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,54): Error RZ3906: The '@page' directive must precede all other elements defined in a Razor file.) (One or more compilation failures occurred:
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,55): Error RZ2005: The 'page` directive must appear at the start of the line.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,59): Error RZ1011: The 'page' directives value(s) must be separated by whitespace.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,54): Error RZ3906: The '@page' directive must precede all other elements defined in a Razor file.) (One or more compilation failures occurred:
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,55): Error RZ2005: The 'page` directive must appear at the start of the line.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,59): Error RZ1011: The 'page' directives value(s) must be separated by whitespace.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,54): Error RZ3906: The '@page' directive must precede all other elements defined in a Razor file.) ---> Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,55): Error RZ2005: The 'page` directive must appear at the start of the line.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,59): Error RZ1011: The 'page' directives value(s) must be separated by whitespace.
C:/Repos/websites/MywebsitE/wyam/input/services/cloud/_layout.cshtml(65,54): Error RZ3906: The '@page' directive must precede all other elements defined in a Razor file.
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Wyam.Razor.WyamRazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromPath(String executingFilePath, String pagePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.GetPage(String executingFilePath, String pagePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.GetLayoutPage(ViewContext context, String executingFilePath, String layoutPath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)

(the list goes on)

```

**Comment by daveaglick** [comment]
I'm pretty sure this is telling us that your `_layout.cshtml` file contains `page` as a variable somewhere and that variable is being used with the `@` syntax. For example:

```
@for(IDocument page in ...)
{
    <div>@page.String("foo")</div>
}
```

The new Razor engine sees the `@page` and isn't smart enough to determine that it's not a directive to use Razor Pages. Search that `_layout.cshtml` for any instances of the string "@page" and then use parens around the "page" part:

```
@for(IDocument page in ...)
{
    <div>@(page.String("foo"))</div>
}
```

**Comment by elvogel** [comment]
Yeah, as a matter of fact, I was using it all over the place. Nice catch!
