### ISSUE TITLE
WYAM.Tool too many files on Posix (macOS, LInux)

### ISSUE THREAD

**Issue by devlead** [statiqdev/Statiq#805]
Running `Wyam.Tool` version `2.2.4` on .NET Core SDK `2.1.602` / Runtime `2.1.9` with the cakebuild.net website on non Windows systems causes "Too many files" open exception.

Repro on macOS / Linux
1. git clone https://github.com/cake-build/website.git
2. cd website
3. ./build.sh

Result:

```
Exception during execution: System.AggregateException: One or more errors occurred. (Too many open files) (Too many open files) (Too many open files) (Too many open files) (Too many open files) (Too many open files) (Too many open files) .... (Too many open files) ---> System.IO.IOException: Too many open files
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Wyam.Core.IO.FileProviders.Local.LocalFile.<OpenWrite>b__19_0()
   at Wyam.Core.IO.FileProviders.Local.RetryHelper.Retry[T](Func`1 func)
   at Wyam.Core.Modules.IO.WriteFiles.Write(IDocument input, IExecutionContext context, FilePath outputPath)
   at Wyam.Core.Modules.IO.WriteFiles.<>c__DisplayClass17_1.<Execute>b__2()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_1.<Invoke>b__0(Object& state, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at Wyam.Core.Modules.IO.WriteFiles.Execute(IReadOnlyList`1 inputs, IExecutionContext context)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments)
   at Wyam.Core.Execution.ExecutionContext.Execute(IEnumerable`1 modules, IEnumerable`1 inputs, IEnumerable`1 items)
   at Wyam.Core.Modules.Control.If.Execute(IReadOnlyList`1 inputs, IExecutionContext context)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 inputDocuments)
   at Wyam.Core.Execution.ExecutionPipeline.Execute(Engine engine, Guid executionId)
   at Wyam.Core.Execution.Engine.Execute()
---> (Inner Exception #0) System.IO.IOException: Too many open files
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Wyam.Core.IO.FileProviders.Local.LocalFile.<OpenWrite>b__19_0()
   at Wyam.Core.IO.FileProviders.Local.RetryHelper.Retry[T](Func`1 func)
   at Wyam.Core.Modules.IO.WriteFiles.Write(IDocument input, IExecutionContext context, FilePath outputPath)
   at Wyam.Core.Modules.IO.WriteFiles.<>c__DisplayClass17_1.<Execute>b__2()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_1.<Invoke>b__0(Object& state, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)<---

---> (Inner Exception #1) System.IO.IOException: Too many open files
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Wyam.Core.IO.FileProviders.Local.LocalFile.<OpenRead>b__18_0()
   at Wyam.Core.IO.FileProviders.Local.RetryHelper.Retry[T](Func`1 func)
   at Wyam.Core.Modules.IO.WriteFiles.Write(IDocument input, IExecutionContext context, FilePath outputPath)
   at Wyam.Core.Modules.IO.WriteFiles.<>c__DisplayClass17_1.<Execute>b__2()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_1.<Invoke>b__0(Object& state, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)<---

```
Full log: [log.txt](https://github.com/Wyamio/Wyam/files/3046976/log.txt)

On my Mac max files per process is 49152, for the Cake website API docs are around 18545 documents, would assume something isn't disposed/some degree of parallelism issue. 

Example macOS / Linux CI failing on Azure DevOps but WIndows ok
https://dev.azure.com/cake-build/website/_build/results?buildId=5176

**Comment by daveaglick** [comment]
From Slack:

@devlead   [11 days ago]
See that you if have a meta data flag in WriteFiles if not set a new stream is opened and returned as result, perhaps that's an issue.

@daveaglick   [11 days ago]
I'm going to guess that we're also holding streams open from reads when we loaded the source code, YAML addin specs, etc.

@daveaglick   [11 days ago]
Thanks for filing the issue

@devlead   [11 days ago]
YAML addins is a separate process so don't think that's the issue. but source / documents etc sure.

@devlead   [11 days ago]
@daveaglick Haven't followed code to deep, but where is this OpenRead disposed?

https://github.com/Wyamio/Wyam/blob/e674d45e96867f3cd3764bf344f4de70a3f3a85f/src/core/Wyam.Core/Modules/IO/WriteFiles.cs#L359-L361

Looks like all `Parallel.Invoke(writesBySource.Values.Select(x => x.Item2).ToArray());`

Where `Item2` is delegate to `Write`

Maybe barking up wrong tree, but looked intresting.

@daveaglick   [11 days ago]
By default, documents dispose the streams passed to them when the document is disposed

@daveaglick   [11 days ago]
The document generally gets disposed when another module is run after it

@devlead   [11 days ago]
Ok but if there's 18k documents?

@daveaglick   [11 days ago]
However, if the module is the last one in a pipeline then the documents don't get disposed until the very end because they're kept as available for other pipelines to use (edited)

@daveaglick   [11 days ago]
Yeah, that would keep 18k open file read handles - probably part of our problem

@daveaglick   [11 days ago]
The very first thought that comes to mind is that I could add functionality to a document to supply a "get my stream" delegate instead of actually passing in a stream

@daveaglick   [11 days ago]
Could also have an option to keep the stream around in the document once someone asked for it or dispose and get a fresh one on each request

@daveaglick   [11 days ago]
The caller API would already support that - callers are supposed to call `IDocument.GetStream()` and dispose the result (right now the disposal mostly does locking to avoid concurrent writes but could be extended to actually dispose the stream and release the file lock until the next request for it)

@daveaglick   [11 days ago]
I'll think on it a bit more and then write up some thoughts in the issue

@devlead   [11 days ago]
Kinda like _"OpenStreamLazy"_

@daveaglick   [11 days ago]
Yeah, exactly - that way for streams that exist outside memory if the document is never used then we never have to open it

@devlead   [11 days ago]
API most likely only one that gets that big, question is if one maybe could batch/shard it some how like _"Skip(x*1000).Take(1000)"_

@devlead   [11 days ago]
A process limit it 24576

For fun doubled it and started a rerun

@devlead   [11 days ago]
Hmm did a lsof and if I'm correct it's 10k files open before api writefiles which makes sense 18k + 10k >  25k

@devlead   [11 days ago]
Ok setting `sudo sysctl -w kern.maxfilesperproc=100000` and it went through, haven't tried how low I can set it :slightly_smiling_face: But at least I can run it on the mac now.
Pasted image at 2019-04-05, 5:13 PM 

@daveaglick   [11 days ago]
Can you set it to Int32.MaxValue :rolling_on_the_floor_laughing:

@devlead   [11 days ago]
Clever :thinking_face::+1:

@devlead   [7 days ago]
@daveaglick Actually didn't help, tried all sorts of things on CI, it just dies around 30k open files. Only managed to build successfully once on my Mac.

**Comment by daveaglick** [comment]
This should be resolved in vnext - it now uses a "content provider" specific to the type of content. For file content the file stream is opened and closed as used so a handle doesn't need to be kept for the lifetime of the document.
